### ISSUE TITLE
✨ Command to open

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditCLI#2]
## Overview

Users need to be able to open files and folders from the command line in CodeEdit.

## Folder

```shell
codeedit ./my-project
```

## File

```shell
codeedit index.html
```

You should also be able to add an optional line and column

```shell
codeedit index.html:50
```

or

```shell
codeedit index.html:50:15
```

## References

- [VS Code implementation](https://code.visualstudio.com/docs/editor/command-line#_opening-files-and-folders)

**Comment by lukepistrol** [comment]
this is already implemented:

```bash
# open the current working directory as a folder
codeedit-cli .

# open a specific file in single file mode
codeedit-cli index.html

# open a specific folder
codeedit-cli ~/Developer/example-project

# open a specific file at a specific line
codeedit-cli index.html -l 42

# open a specific file at a specific line and column
codeedit-cli index.html -l 42 -c 3
```

<img width="524" alt="Screenshot 2022-12-06 at 05 05 49" src="https://user-images.githubusercontent.com/9460130/205870435-3f4839d0-44bf-40c3-9581-925413c56297.png">
