### ISSUE TITLE
Change `codeedit-cli` to `codeedit`

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditCLI#20]
I'd like to propose that we shorten the name of our CLI. `codeedit-cli` is to long of a command to type into a terminal in my opinion.

VS Code uses `code`
GitHub uses `gh`
IntelliJ IDEA uses `idea`
Fleet used `fleet`
Atom uses `atom`
Sublime Text uses `subl`
Nova uses `nova`
WebStorm uses `webstorm`

But CodeEdit uses `codeedit-cli`.

None of these end with `-cli`, so why would/should we? I am not opposed to it, I just want to be consistent with what others might expect if possible. It looks like others just use the app name unless too long to type. `codeedit` is the same amount of characters as `webstorm` so I think it is safe to use.

Some other options we can consider in addition to `codeedit` are `cedit` and `ce`.

**Comment by clayton256** [comment]
Using `cli` or `ctl` and the end is not unheard of. My opinion is to leave it as is. If you want something else make and alias.

**Comment by austincondiff** [comment]
It’s not all about being unheard of. Length is also a big consideration. `codeedit` by itself is already pretty long for a CLI tool.

**Comment by lukepistrol** [comment]
Since #21 the executable is now named `codeedit`
