### ISSUE TITLE
codeedit: Create a file if it does not exist

### ISSUE THREAD

**Issue by onl1ner** [CodeEditApp/CodeEditCLI#32]
Currently `codeedit` command just opens existing files and fails if you try to use it to create one. It would be more convenient if command will create and open a file if it does not exist and just open if it exist (e.g. `code` on VSCode works this way)

**Comment by activcoding** [comment]
What behaviour are we aiming for here? Should the command `codeedit create project` and `codeedit create index.js` be distinct, or should `codeedit index.js` automatically create the file if it doesn't exist in the current directory? I can see how `codeedit create` might be clearer for beginners, but personally, I'm used to using commands like `nvim index.js` to create files.

**Comment by onl1ner** [comment]
I expect `codeedit` command to automatically create and open a file if it doesn't exist, with the name passed as an argument of the command. So you are not constrained to have a file to open it

**Comment by activcoding** [comment]
Thanks for clearing that up. I'll catch up with the other maintainers later. I've got the functionality in place as you described them, but I want to touch base with them first.

**Comment by matthijseikelenboom** [comment]
Also, should it be possible to do something like `codeedit path/to/file.js` and that it then also create the folders if they don't exist?

**Comment by onl1ner** [comment]
VSCode `code` command works this way, I think it would be nice to cover this case.
