### ISSUE TITLE
✨ Flag to goto specific line and optional column

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditCLI#6]

**Comment by lukepistrol** [comment]
The current implementation already supports this:

```bash
$ codeedit-cli Example.swift -l 43 -c 10
$ codeedit-cli Example.swift -l 43
```

<img width="524" alt="Screenshot 2022-12-06 at 05 05 49" src="https://user-images.githubusercontent.com/9460130/205868697-ff817d11-af07-4e68-a982-e7fdbe94c319.png">

**Comment by austincondiff** [comment]
I was referring to [VS Code documentation](https://code.visualstudio.com/docs/editor/command-line#_core-cli-options) where it says `--goto` or `-g` is used when opening a file.
> This argument is provided since some operating systems permit : in a file name. 
However macOS does not allow `:` in filenames, so this is not necessary.
